### ISSUE TITLE
Odoo 12 

### ISSUE THREAD

**Issue by jfreres** [katyukha/odoo-rpc-client#5]
Search_read sale.subscription fails TypeError: cannot marshal <class 'datetime.date'> objects

**Comment by katyukha** [comment]
Hello!
Thanks for this bug report!

Can you provide more information? Example of code-line that produces this error? What protocol is used: xmlrpc or jsonrpc? Version of python used: python2 or python3?

**Comment by katyukha** [comment]
Hello!

It seems that Odoo have fixed this bechavior in 12.0 by commit odoo/odoo@2693918903483f10e18583b2ba716c4a9667320a

**Comment by jfreres** [comment]
Is it possible to set a timeout in the extra_args = dict(extra_args, timeout=1200)? 
env = Client(host='',
            dbname='',
            user='',
            pwd='', 
            port=80,
            protocol='json-rpc',             
            **extra_args)

**Comment by katyukha** [comment]
New version will be released in few days. I will add this feature in new release.

**Comment by jfreres** [comment]
Awesome.  Some long running tasks such as stock moves gateway timeout on odoo.sh if the timeout reaches 900s.  I'm happy to test when the new release is ready.

**Comment by katyukha** [comment]
Hello! I have added timeout support for dev version. It is available on [gitlab repository](https://gitlab.com/katyukha/odoo-rpc-client/tree/dev)

As for odoo.sh, there may be timeouts set on server side, and this error may be not related to client app.

**Comment by jfreres** [comment]
Thanks.  This is working fine.  I agree if odoo.sh sets a low cpu or the like this will not work.

**Comment by katyukha** [comment]
I have finally released 1.0.0 release)
All changes are there, thus i am closing this issue.

Thanks for reporting)
